name: auto-update-config

on:
  workflow_dispatch:
  schedule: # 计划任务触发
    - cron: '0 23 * * *'

jobs:

  run-daily-task:

    runs-on: ubuntu-latest
    
    steps:
      
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x
          
      - name: Setup env
        env:
          JSON_CONFIG_URL: ${{secrets.JSON_CONFIG_URL}}
        run: |
          echo "Setting JSON_CONFIG_URL to $JSON_CONFIG_URL"
          export JSON_CONFIG_URL=$JSON_CONFIG_URL
      
      - name: Run
        run: |
          cd ./src/AutoClash.ConsoleApp
          dotnet run --environment "JSON_CONFIG_URL=$JSON_CONFIG_URL"