name: auto-update-config

on:
  workflow_dispatch:
  schedule: # 计划任务触发
    - cron: '0 22 * * *'

jobs:

  run-daily-task:

    runs-on: ubuntu-latest
    
    steps:
      
      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
      - name: Checkout
        uses: actions/checkout@main
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Run
        run: |
          cd ./src/AutoClash.ConsoleApp
          dotnet run --config-url ${{secrets.JSON_CONFIG_URL}} -c Release
